feat: add knip CI configuration
ubiquity/ts-template pull request #13
Opened 2024-02-19 21:36 UTC by gitcoindev

Resolves: https://github.com/ubiquity/ts-template/issues/12

2024-02-19 21:40 UTC, pavlovcik reviewed
This is functional right? Last time I tried it, it didn't work. Can you test?

2024-02-19 21:43 UTC, gitcoindev commented
Hi @pavlovcik I ported knip CI almost 1:1 from ubiquibot. Integration looks good , but failing with 
```
  - Create check ID
Error: 🧨 Failed: Resource not accessible by integration
Error: 📚 Stack: HttpError: Resource not accessible by integration
```
this is due to lack of permission in the `ts-template` repository to add pull request comments from GitHub actions. If I remember correctly we saw it already. The permission is required by Codex-/knip-reporter@v2 and the error can be resolved by comparing settings on bot repository and enabling write comment access.

2024-02-19 21:56 UTC, gitcoindev commented
Yes, I can confirm this works on my fork with write settings enabled. QA: https://github.com/gitcoindev/ts-template/pull/1

2024-02-19 22:48 UTC, pavlovcik commented
> comparing settings on bot repository and enabling write comment access.

Can you elaborate? Would like to fix this!

2024-02-20 06:58 UTC, gitcoindev commented
> > comparing settings on bot repository and enabling write comment access.
> 
> Can you elaborate? Would like to fix this!

Yes sure,

Settings->Actions>General>Workflow permissions->Select 'Read and Write permissions'.

Choose the default permissions granted to the GITHUB_TOKEN when running workflows in this repository. You can specify more granular permissions in the workflow using YAML. [Learn more about managing permissions.](https://docs.github.com/actions/reference/authentication-in-a-workflow#modifying-the-permissions-for-the-github_token)



Read and write permissions

2024-02-20 07:18 UTC, pavlovcik commented
Perhaps we can auth it with our bot? This way we don't have to manually change the settings for all our repositories. 

All the values necessary are in our org secrets! Check out my logic for posting the comment as the bot in @ubiquity/cloudflare-deploy-action!

2024-02-20 07:20 UTC, 0x4007 requested changes

2024-02-20 07:20 UTC, 0x4007 commented on .github/workflows/knip.yml
> +        uses: actions/setup-node@v3
```suggestion
        uses: actions/setup-node@v4
```

2024-02-20 07:20 UTC, 0x4007 commented on .github/workflows/knip.yml
> +        uses: actions/checkout@v3
```suggestion
        uses: actions/checkout@v4
```

2024-02-20 07:20 UTC, 0x4007 commented on .github/workflows/knip.yml
> +          node-version: 20.10.x
```suggestion
          node-version: 20.10.0
```

2024-02-20 07:30 UTC, gitcoindev commented on .github/workflows/knip.yml
> +          node-version: 20.10.x
done

2024-02-20 07:30 UTC, gitcoindev commented on .github/workflows/knip.yml
> +        uses: actions/checkout@v3
done

2024-02-20 07:30 UTC, gitcoindev commented on .github/workflows/knip.yml
> +        uses: actions/setup-node@v3
done

2024-02-20 07:33 UTC, pavlovcik approved these changes

2024-02-20 07:33 UTC, merged

2024-02-20 07:33 UTC, gitcoindev commented
> Perhaps we can auth it with our bot? This way we don't have to manually change the settings for all our repositories.
> 
> All the values necessary are in our org secrets! Check out my logic for posting the comment as the bot in @ubiquity/cloudflare-deploy-action!

An interesting idea. I will try to experiment on that and try to submit a solution till today eod.

2024-02-20 08:05 UTC, pavlovcik commented
Use this as inspiration. The same exact property names should work for any repository under @ubiquity. 

https://github.com/ubiquity/cloudflare-deploy-action/blob/main/src/handle-commit.ts