Implement Pascal Case for Erc20Permit and Erc721Permit
ubiquity/ts-template pull request #40
Opened 2024-04-19 11:37 UTC by jordan-ae

… naming conventions

Resolves #39

2024-04-19 12:35 UTC, 0x4007 commented
Thank you but this should be generalized for every identifier not just those two.

2024-04-19 12:36 UTC, 0x4007 requested changes
You also should not change any other files.

2024-04-19 12:36 UTC, 0x4007 commented on .eslintrc
> +          "regex": "^(Erc20Permit|Erc721Permit)$",
Thank you for your pull but this should be generalized for every identifier not just those two.

2024-04-19 12:40 UTC, jordan-ae commented
> You also should not change any other files. 

@0x4007 The other modifications were made my running the linters. If you check the changes you'll see the linters just added spaces where it seemed necessary and all that. I can revert the changes if they will cause any issues though.

2024-04-19 13:04 UTC, jordan-ae commented on .eslintrc
> +          "regex": "^(Erc20Permit|Erc721Permit)$",
If I understand what you mean by identifier: variables, types, functions, and labels should all follow pascal case?

2024-04-21 01:04 UTC, gentlementlegen commented
There actually already is a rule for `PascalCase` interfaces, no need to create a new one. The thing is that rule enforces `Pascal Case` but not strictly meaning you can chain uppercase letters.

If we want to prevent this we can use `StrictPascalCase`. Maybe it would be a good idea to use it everywhere @0x4007 ?
See also: https://typescript-eslint.io/rules/naming-convention/#format-options

2024-04-21 07:25 UTC, 0x4007 commented
That rule seems to only check for the first character being capitalized according to the docs. I think a regex that looks for three or more consecutive capitalized letters should be flagged as an error

2024-04-21 07:34 UTC, gentlementlegen commented
`StrictPascalCase` will enforce no more that one capital letter inside the name, regardless of the position. Example:
<img width="727" alt="image" src="https://github.com/ubiquity/ts-template/assets/9807008/03b01d2a-31d6-4419-aaa7-9adcc3289fb7">
Quoting the docs: "consecutive capitals are not allowed (i.e. myId is valid, but myID is not)."

2024-04-21 07:37 UTC, 0x4007 commented
I think let's use strictpascalcase then!

2024-04-22 03:20 UTC, gentlementlegen commented
@0x4007 Shall this be applied to other elements too, like variables etc? There is the same version for camel case called `StrictCamelCase`.

2024-04-22 03:45 UTC, 0x4007 commented
Yes let's apply this across all identifiers.

2024-04-23 02:00 UTC, jordan-ae commented
@0x4007, @gentlementlegen  I've added StrictPascalCase to the eslint rules. They'll be a couple of errors in certain files due to the new eslint configuration which I haven't changed because of this comment. I'd love to clean up the files though!

> You also should not change any other files.

I also suggest we create a pre-commit hook. By doing so we can ensure no errors go into the repository and enforce code style. The pre-commit hook will run only on staged files to avoid slow and irrelevant processes.

2024-04-23 02:22 UTC, 0x4007 commented
We have lint-staged for this purpose but perhaps it's not configured correctly.

2024-04-23 02:24 UTC, jordan-ae commented
> We have lint-staged for this purpose but perhaps it's not configured correctly. 

Okay I'll take sometime to look into that too

2024-04-25 10:15 UTC, jordan-ae commented
@gentlementlegen please can you review? Thanks

2024-04-25 11:08 UTC, gentlementlegen approved these changes
I am fine with the changes per se, but the changes outside of `.eslintrc` don't seem directly related to this PR but to your own IDE settings.

2024-04-25 14:36 UTC, jordan-ae commented
@0x4007 I guess this is ready to go

2024-04-29 02:15 UTC, jordan-ae commented
Hey @0x4007 I've undone all the changes not related to the issue. This should be ready to go now!

2024-05-02 08:03 UTC, gentlementlegen commented on .eslintrc
> +      { "selector": "variableLike", "format": ["StrictPascalCase"] },
We should not change the `camelCase` to `StrictPascalCase` but `strictCamelCase` instead.

2024-05-02 08:03 UTC, gentlementlegen commented on .eslintrc
> -      { "selector": "variable", "format": ["camelCase", "UPPER_CASE"], "leadingUnderscore": "allow", "trailingUnderscore": "allow" },
`UPPER_CASE` should not be removed.

2024-05-02 08:04 UTC, gentlementlegen requested changes
Do not make changes that would change the behavior of the configuration. We just need `StrictPascalCase` and `strictCamelCase` over the `PascalCase` and `camelCase` respectively.

2024-05-02 13:39 UTC, jordan-ae commented
> I think let's use strictpascalcase then!I 

I thought we were going full in on StrictPascalCase 😬

2024-05-03 03:42 UTC, gentlementlegen approved these changes

2024-05-03 04:25 UTC, 0x4007 approved these changes

2024-05-03 04:25 UTC, 0x4007 approved these changes

2024-05-03 04:25 UTC, 0x4007 approved these changes

2024-05-03 04:25 UTC, merged